// Code generated by tygo. DO NOT EDIT.
// From internal/protocol, by `npm run gen:protocol` (tygo). CI fails when
// this file is stale; edit the Go types, never this file.

//////////
// source: errors.go

/**
 * Error is the wire error. Code is the stable machine identifier; Message is
 * human text in English. Localisation, if it ever exists, hangs off Code and
 * never off Message.
 */
export interface Error {
  code: string;
  message: string;
}
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeSessionNotFound = "session_not_found";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeTurnAlreadyActive = "turn_already_active";
/**
 * CodeNoActiveTurn answers a correction aimed at a turn that is not
 * running. Distinct from turn_already_active and its exact mirror: one says
 * "wait", the other says "there is nothing to correct — send it as a
 * message". Collapsing them would leave the client guessing which.
 */
export const CodeNoActiveTurn = "no_active_turn";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeInvalidInput = "invalid_input";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeApprovalResolved = "approval_already_resolved";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeApprovalExpired = "approval_expired";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeEventsExpired = "events_expired";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeWorkspaceInvalid = "workspace_invalid";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeMaxSessionsReached = "max_sessions_reached";
/**
 * Error codes. Section 8 of the planning spec.
 */
export const CodeInternal = "internal";

//////////
// source: protocol.go
/*
Package protocol is the shared vocabulary between the dcode daemon and its
clients. It holds no logic and performs no I/O: both sides import it so the
wire contract has exactly one definition.

Spec: docs/specs/architecture/client-server-protocol/202608072240-*.
*/

/**
 * Version is the protocol version carried in the URL prefix.
 */
export const Version = "v1";
/**
 * EventType identifies the payload shape of an Event.
 */
export type EventType = string;
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventSessionCreated: EventType = "session.created";
/**
 * EventSessionResumed opens the conversation this session continues.
 * The events after it happened somewhere else, and a marker is what keeps
 * the transcript honest about that: without one, a replayed conversation
 * reads as work this session did. It also carries the only thing the reader
 * cannot reconstruct from the events themselves — which session they came
 * from.
 */
export const EventSessionResumed: EventType = "session.resumed";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventTurnStarted: EventType = "turn.started";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventMessageDelta: EventType = "message.delta";
/**
 * EventMessageReasoning carries the model's thinking, which is not its
 * answer. It is an event so a client can show it and so replaying a session
 * looks like having watched it — but it never enters the history the model
 * is sent, because a model that reads its own reasoning back as something
 * it said out loud starts defending it.
 */
export const EventMessageReasoning: EventType = "message.reasoning";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventToolRequested: EventType = "tool.requested";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventApprovalRequired: EventType = "tool.approval_required";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventApprovalResolved: EventType = "tool.approval_resolved";
/**
 * EventDoneProposed carries a measured definition of done to the operator.
 * Measured, not merely proposed: every criterion in it has already been run
 * against the repository as it stands, and each one says what that run did.
 * A proposal without those results is a list of good intentions.
 */
export const EventDoneProposed: EventType = "done.proposed";
/**
 * EventDoneSigned announces the definition of done the operator signed,
 * which is the one the turn is measured by and not necessarily the one that
 * was proposed.
 */
export const EventDoneSigned: EventType = "done.signed";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventToolCompleted: EventType = "tool.completed";
/**
 * EventTurnSteered is the person correcting a turn already under way.
 * Its own event rather than a message delta: a correction the transcript
 * cannot tell apart from the model's own words is a turn nobody can audit
 * afterwards, and "why did it change direction" is the first question asked
 * of any run that went sideways.
 */
export const EventTurnSteered: EventType = "turn.steered";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventTurnCompleted: EventType = "turn.completed";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventPlanUpdated: EventType = "plan.updated";
/**
 * EventProgress answers "how far along", and it is the only event here
 * that is not a fact worth replaying on its own.
 * One event rather than one per question. A tool counting files and a turn
 * counting rounds are the same question asked of different subjects, and
 * adding a versioned surface twice for one kind of question is how it comes
 * out crooked — the second one always answers slightly differently.
 * It joins the log and the record like message.delta does: chatty, batched
 * rather than flushed, and carrying a Seq. Giving it no Seq would have been
 * the alternative, and it would have put a gap in the one property the
 * record is built on.
 */
export const EventProgress: EventType = "progress";
/**
 * EventSessionRenamed is a name a person gave this conversation.
 * An event rather than a file beside the record, and the record is where it
 * belongs for one reason above the others: a name for a conversation that
 * no longer exists is nothing. Pruning removes the transcript, and a name
 * stored anywhere else would outlive what it named — a listing full of
 * titles for sessions nobody can open.
 * It also keeps the count at one. A second store beside the log is a second
 * thing that can disagree with the first, and this protocol's whole shape
 * is that every observable fact travels the same way.
 */
export const EventSessionRenamed: EventType = "session.renamed";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventSessionCompacted: EventType = "session.compacted";
/**
 * EventSkillLoaded announces a skill body entering the turn.
 * The index is auditable — it is in the prefix, and `--dump-prompt` prints
 * it. The body was not: it was appended to the history as a reminder with
 * nothing emitted, so a block of text joined the turn, cost tokens and
 * changed how the model behaved, with no way for the person to know it had
 * happened or which skill it was.
 * Thirty lines above the injection, the same package refuses to drop a
 * skill from the index in silence. This is the sentence at the top of this
 * block applied to the one observable fact that was not travelling.
 */
export const EventSkillLoaded: EventType = "skill.loaded";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventContextBand: EventType = "context.band";
/**
 * Event types. Payload shapes are defined in section 5.1 of the planning spec.
 */
export const EventSessionError: EventType = "session.error";
/**
 * EventSessionModeChanged announces a switch between plan, assist and auto.
 * Carried over the event log rather than read from a side channel so a
 * client that attaches after the change still sees what the session is
 * running under, the same way SessionCreated already does for the original.
 */
export const EventSessionModeChanged: EventType = "session.mode_changed";
/**
 * WorkspaceDoneDir is the workspace's own definition-of-done directory.
 * It is where a proposal lands when no spec folder claims it — a goal typed as
 * a sentence — and it lives here because both halves need it: the client
 * decides to anchor there, and the daemon writes there. It was a literal in
 * two places before that was true of only one of them.
 */
export const WorkspaceDoneDir = ".dcode";
/**
 * Mode names. The behavioural mode is what the user picks; the wire carries the
 * name, and Session.SetMode maps it to the pair of (SandboxMode, Policy) the
 * engine actually runs under.
 */
export const ModePlan = "plan";
/**
 * Mode names. The behavioural mode is what the user picks; the wire carries the
 * name, and Session.SetMode maps it to the pair of (SandboxMode, Policy) the
 * engine actually runs under.
 */
export const ModeAssist = "assist";
/**
 * Mode names. The behavioural mode is what the user picks; the wire carries the
 * name, and Session.SetMode maps it to the pair of (SandboxMode, Policy) the
 * engine actually runs under.
 */
export const ModeAuto = "auto";
/**
 * Event is the envelope every observable fact travels in. Seq is per session,
 * monotonic from 1, never reused and never gapped.
 * At is the only non-deterministic field; golden comparisons zero it.
 */
export interface Event {
  seq: number /* uint64 */;
  session_id: string;
  type: EventType;
  at: string;
  payload: unknown;
}
/**
 * SessionState is the lifecycle state of a session.
 */
export type SessionState = string;
export const SessionStateIdle: SessionState = "idle";
export const SessionStateRunning: SessionState = "running";
export const SessionStateBlocked: SessionState = "blocked";
export const SessionStateClosed: SessionState = "closed";
/**
 * Session is the server-owned session record. Clients hold no session state of
 * their own beyond scroll position, panel visibility and their input queue.
 */
export interface Session {
  id: string;
  state: SessionState;
  workspace: string;
  model: string;
  /**
   * Family, Transport and BaseURL are the rest of the bundle a name like
   * `qwen-local` resolves to (202608072334-provider-adapter.p.spec.md §2.2).
   * Carried so a resumed session can reconnect to the same endpoint rather
   * than falling back to whatever `model.name` resolves to on the machine
   * that types `dcode -c` — empty means the family's own default, the same
   * reading `model.family`/`model.transport`/`model.base_url` already give
   * an unset override.
   */
  family?: string;
  transport?: string;
  base_url?: string;
  /**
   * Branch is the git branch the workspace was on when this session was
   * built, frozen at that moment like the rest of the session's facts.
   * Empty when the workspace has no repository, git is not installed, or
   * the head is detached — the status bar draws nothing for it then, the
   * same reading "no data" already gets everywhere else on that bar.
   */
  branch?: string;
  sandbox_mode: string;
  /**
   * Mode is the behavioural mode the session runs under: plan, assist or
   * auto. Defaults to assist when the request does not set it. SandboxMode is
   * the technical consequence; Mode is the name the user picks.
   */
  mode: string;
  created_at: string;
  last_seq: number /* uint64 */;
  /**
   * FirstSeq is the earliest event the session still holds. It is not always
   * 1: continuing a long conversation puts every carried event in the log,
   * and retention drops the oldest. A client that assumes 1 asks for events
   * that are gone and is refused, so the session it asked for never opens.
   */
  first_seq?: number /* uint64 */;
  /**
   * ContextWindow is the model's window in tokens. The client needs it to
   * turn a token count into the percentage a person can act on; without it,
   * "12400 tokens" answers nothing.
   */
  context_window?: number /* int */;
  /**
   * DoneCriteria is how many criteria this session is measured against.
   * Zero is a real answer and the one worth carrying: a session with no
   * definition of done reports done at the end of the first turn, and asking
   * for a spec and getting zero is exactly the moment someone needs to be
   * told. Without this the client would have to say "loop opened" and mean
   * nothing by it.
   */
  done_criteria: number /* int */;
}
/**
 * CreateSessionRequest opens a session. Workspace must be absolute.
 */
export interface CreateSessionRequest {
  workspace: string;
  model?: string;
  sandbox_mode?: string;
  /**
   * Resume names a recorded session whose conversation this one continues.
   * A new session either way: the old one ended with the client that ran it,
   * and nothing survives what created it. What carries over is the history,
   * rebuilt from the record — not the approvals, which were consent given in
   * a moment that has passed, and not the background processes, which died
   * with the session that started them.
   */
  resume?: string;
  /**
   * LoopSpec is a directory holding a tasks.md, read as this session's
   * definition of done.
   * A path rather than the parsed criteria: the client may be nowhere near
   * the daemon's filesystem, and a client that read the spec itself would be
   * asserting what a file it cannot see contains. Relative to the workspace,
   * and refused if it climbs out of it.
   */
  loop_spec?: string;
  /**
   * Protect are globs added to whatever the spec declares as protected.
   * Union, never precedence: Protected surfaces a change rather than
   * forbidding it, so an argument must not be able to REMOVE a protection
   * the file asked for.
   */
  protect?: string[];
  /**
   * Qualify opens the session that works out what "done" means for LoopSpec,
   * rather than the one that does the work.
   * The LOOP decides there is a qualifying session, not the model: reading,
   * projecting and qualifying are what the loop does before it executes, and
   * a model that chose when to qualify would be choosing when to be measured.
   * It runs in plan mode, always — deciding what you will be measured by is
   * reading, and an agent that could write while deciding can move the thing
   * it is about to be measured against.
   */
  qualify?: boolean;
}
/**
 * ExecRequest runs a command the person typed, outside a turn.
 * Its own request rather than a flag on SubmitTurnRequest: submitting starts a
 * turn and this one does not. The command runs through the same tool, under the
 * same sandbox and the same approvals, and its output is put in the history as
 * something the user did — because they did.
 */
export interface ExecRequest {
  command: string;
}
/**
 * SubmitTurnRequest submits user input. Rejected with turn_already_active if a
 * turn is already running: one turn per session.
 */
export interface SubmitTurnRequest {
  text: string;
  /**
   * Images are pictures shown with this turn, base64 encoded with their
   * media type. Sent by value rather than as paths: the daemon may be on
   * another machine, and a path only means something where it was typed.
   */
  images?: TurnImage[];
}
/**
 * TurnImage is one picture on the wire.
 */
export interface TurnImage {
  media_type: string;
  data: string;
}
/**
 * UndoResult is what putting the last turn back changed, and what it would not
 * touch.
 * Refused is per file rather than all-or-nothing: seven files changed and one
 * edited by hand should still give six back, and naming the one that stayed is
 * more useful than refusing everything on account of it.
 */
export interface UndoResult {
  restored: string[];
  refused: string[];
}
/**
 * ApprovalDecision is the user's answer to a boundary crossing.
 */
export type ApprovalDecision = string;
export const ApprovalAllow: ApprovalDecision = "allow";
export const ApprovalAllowSession: ApprovalDecision = "allow_session";
export const ApprovalDeny: ApprovalDecision = "deny";
/**
 * The two answers that outlive the session, because some questions are
 * about the project rather than about the moment. Asking again next week
 * about a decision already made is how a prompt becomes something people
 * dismiss without reading — and a prompt nobody reads protects nobody.
 * They are recorded in the USER's config root, never in the workspace: a
 * grant living inside a project would let a repository arrive
 * pre-approved, so cloning something would permit it before anyone read a
 * line of it.
 */
export const ApprovalAllowProject: ApprovalDecision = "allow_project";
export const ApprovalAllowAlways: ApprovalDecision = "allow_always";
/**
 * RenameSessionRequest names a conversation. An empty name restores the title
 * derived from the first question, which is the way back rather than a second
 * command for undoing.
 */
export interface RenameSessionRequest {
  name: string;
}
/**
 * ResolveApprovalRequest answers a pending approval. First writer wins.
 */
export interface ResolveApprovalRequest {
  decision: ApprovalDecision;
}
/**
 * CompactResult answers a forced compaction directly, alongside whatever
 * EventSessionCompacted already carried to an attached client. The event
 * says nothing when there was nothing worth compacting; this is the one
 * place that says so.
 */
export interface CompactResult {
  compacted: boolean;
}
/**
 * ApprovalRequest is emitted when execution crosses the sandbox boundary. The
 * turn blocks until it is resolved or ExpiresAt passes, which denies.
 * ExpiresAt is set before the question is announced, and it is the instant the
 * approver denies at, so a client can count down to it. The zero time means
 * whoever answers has no deadline — a terminal waits as long as the person
 * takes.
 */
export interface ApprovalRequest {
  approval_id: string;
  turn_id: string;
  tool_call_id: string;
  tool: string;
  command?: string;
  boundary_crossed: string;
  expires_at: string;
  /**
   * Reason says why in a sentence, and Rule names the pattern that raised the
   * question when one did. Consent to a rule nobody can see is consent to
   * nothing, and Rule is also what an "allow for the session" answer is
   * remembered against.
   */
  reason?: string;
  rule?: string;
}
/**
 * DoneProposal is a measured definition of done, waiting for a signature.
 * The turn blocks until it is signed or ExpiresAt passes, which REFUSES. A
 * deadline that approved would be the quietest way to start a turn against a
 * ruler nobody read.
 */
export interface DoneProposal {
  proposal_id: string;
  turn_id: string;
  round: number /* int */;
  criteria: DoneCriterion[];
  protected?: string[];
  /**
   * NoAcceptance says nothing in the set is red. Such a set reports done
   * without anything having to change — usually a defect, and legitimately a
   * refactor. Named, never refused.
   */
  no_acceptance?: boolean;
  expires_at: string;
}
/**
 * DoneCriterion is one criterion as the operator sees it: what was proposed,
 * what was claimed about it, and what running it actually did.
 */
export interface DoneCriterion {
  name: string;
  command: string;
  exit_code: number /* int */;
  expects?: string;
  why?: string;
  class: string;
  exit: number /* int */;
  output?: string;
  /**
   * Mismatch is the proposer's claim disagreeing with the measurement. Not an
   * error and not a rejection: it is where the operator's eye should land.
   */
  mismatch?: boolean;
}
/**
 * SignDoneRequest is the operator's answer.
 * It carries the definition of done AS THEY LEFT IT, not a verdict on the one
 * proposed. A binary gate would turn "I disagree with item 3" into "redo
 * everything", and that cost lands on the operator until they stop disagreeing.
 */
export interface SignDoneRequest {
  proposal_id: string;
  signed: boolean;
  criteria: DoneCriterion[];
  protected?: string[];
}
/**
 * CommitDoneResponse is what came of writing a proposed definition of done.
 */
export interface CommitDoneResponse {
  /**
   * Path is the file the proposal was written to.
   */
  path: string;
  /**
   * Summary is what a person reads: every criterion, and what running it did
   * before any work happened.
   */
  summary: string;
  /**
   * Criteria is how many were written.
   */
  criteria: number /* int */;
}
/**
 * SpecFolder is one spec folder and where it stands.
 * Where it stands, not what it declares: "pending" is answered by running the
 * folder's own criteria, because a checkbox in a tasks.md is marked by whoever
 * felt like marking it.
 */
export interface SpecFolder {
  path: string;
  criteria: number /* int */;
  unmet: number /* int */;
  unavailable?: number /* int */;
  /**
   * Pending is the answer the client acts on, decided by the daemon so two
   * clients cannot disagree about what counts as work left.
   */
  pending: boolean;
  /**
   * Measured says the criteria were actually run to decide Pending.
   * False when the caller asked only what each folder DECLARES, which is a
   * read and costs nothing. Pending is not an answer then, and the field
   * exists so a client cannot mistake "not measured" for "not pending".
   */
  measured: boolean;
  error?: string;
}
/**
 * ListSpecsResponse answers "what is there and what is left".
 */
export interface ListSpecsResponse {
  specs: SpecFolder[];
}
/**
 * PlanItem is one entry of the session plan, maintained by the plan tool.
 */
export interface PlanItem {
  id: number /* int */;
  text: string;
  status: string;
  blocked?: string;
}
/**
 * Plan item statuses.
 */
export const PlanPending = "pending";
/**
 * Plan item statuses.
 */
export const PlanActive = "active";
/**
 * Plan item statuses.
 */
export const PlanDone = "done";
/**
 * Plan item statuses.
 */
export const PlanBlocked = "blocked";
/**
 * PlanUpdated is the payload of EventPlanUpdated.
 */
export interface PlanUpdated {
  items: PlanItem[];
}
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopDone = "done";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopInterrupted = "interrupted";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopMaxIterations = "max_iterations";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopRepeatLoop = "repeat_loop";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopMaxTokens = "max_tokens";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopError = "error";
/**
 * StopUnverified and StopIncomplete are RESULTS, not errors. They are the
 * honest state of work delivered without a check having passed.
 * Treating them as failure would create exactly the wrong incentive: the
 * easy way out becomes switching the checking off.
 */
export const StopUnverified = "unverified";
/**
 * Turn stop reasons, carried in TurnCompleted.Reason.
 */
export const StopIncomplete = "incomplete";
/**
 * ProgressRounds is the turn against its iteration ceiling.
 */
export const ProgressRounds = "rounds";
/**
 * ProgressInFlight is how many tool calls are running together, against
 * the concurrency ceiling this session allows.
 */
export const ProgressInFlight = "in_flight";
/**
 * ProgressArguments is a tool call still arriving from the model, counted
 * in bytes of its arguments.
 * Bytes rather than lines: what has landed is a fragment of JSON, and
 * counting lines inside half an escaped string counts something that is
 * not there yet. It has no total — the model does not say how long the
 * call will be, and a denominator nobody sent is one somebody would trust.
 */
export const ProgressArguments = "arguments";
/**
 * ProgressFiles is a scan working through files. Total is known when the
 * tool had the list before it started and absent when it is still walking.
 */
export const ProgressFiles = "files";
/**
 * TurnStarted announces an accepted input.
 * SteerRequest is what the person says to a turn already running.
 */
export interface SteerRequest {
  text: string;
}
/**
 * TurnSteered is what the person said while the turn was running, and the
 * round it landed at.
 */
export interface TurnSteered {
  turn_id: string;
  text: string;
}
/**
 * Payloads for the remaining event types.
 */
export interface TurnStarted {
  turn_id: string;
  /**
   * Text is what the user asked for.
   * It rides here because a turn starts BECAUSE of it, and because
   * nothing else carried it: the log held the model's side of a
   * conversation and none of the questions. A transcript could not be
   * read, a session could not be titled, and a client attaching to a
   * session already under way saw answers to questions it never saw.
   */
  text?: string;
}
/**
 * MessageReasoning is a fragment of the model's thinking.
 */
export interface MessageReasoning {
  turn_id: string;
  text: string;
}
/**
 * MessageDelta is a fragment of model text.
 */
export interface MessageDelta {
  turn_id: string;
  text: string;
}
/**
 * ToolRequested announces a tool call before policy evaluation.
 */
export interface ToolRequested {
  turn_id: string;
  tool_call_id: string;
  name: string;
  input: unknown;
  /**
   * Typed marks a call the PERSON asked for, through `!`, rather than one
   * the model asked for.
   * The two want opposite things on screen. A model's call is a means: it
   * runs `ls` to orient itself and then says what mattered, so the output
   * collapses and the prose carries the point. A typed command IS the
   * point — someone wrote `ls -la` because they want to see `ls -la`, and
   * collapsing it hides the only thing they asked for.
   * Carried on the event rather than inferred from the call id, because
   * an id's shape is not a fact about who wanted the call.
   */
  typed?: boolean;
}
/**
 * ApprovalResolved records the decision that unblocked a turn.
 */
export interface ApprovalResolved {
  approval_id: string;
  decision: ApprovalDecision;
}
/**
 * ToolCompleted carries the result of an execution.
 */
export interface ToolCompleted {
  tool_call_id: string;
  ok: boolean;
  output: string;
  truncated: boolean;
  /**
   * What the call did, stated once by the tool that knows.
   * A client that parses Output to rebuild these numbers breaks silently
   * the day the wording changes, and every client has to reimplement the
   * same parsing. All optional: a tool reports what applies to it.
   */
  lines?: number /* int */;
  files?: number /* int */;
  added?: number /* int */;
  removed?: number /* int */;
  exit_code?: number /* int */;
  has_exit?: boolean;
  duration_ms?: number /* int */;
  /**
   * StartedAt and FinishedAt are the REAL execution order (RN-3.3).
   * A duration cannot answer which of two concurrent calls went first,
   * and results arrive in emission order rather than the order they ran.
   * A client showing a batch has a person looking at it, and "which of
   * these happened first" is a reasonable thing for them to ask.
   * They live HERE and never in the context sent to the model: a
   * timestamp in the prefix would make two runs of the same session
   * differ, which ADR-03 forbids. The event is a person's window; the
   * context is not.
   */
  started_at?: string;
  finished_at?: string;
  /**
   * Diff is the unified diff of a change. Present only for tools that
   * modify a file, and never part of what the model was sent.
   */
  diff?: string;
}
/**
 * Progress is how far along something running has got.
 * Done without Total is honest: a scan that has not finished enumerating
 * knows how many it has seen and not how many there are. A client shows the
 * count alone rather than inventing a denominator.
 * Kind comes from the closed set below rather than being a word to print.
 * The daemon's language is not the reader's, and a client that renders the
 * payload's text shows the wrong one to half its users.
 * Never part of the context the model is sent: it is a person's window, the
 * same rule StartedAt already carries, and a count that changes between two
 * runs of one session is exactly what ADR-03 forbids in a prefix.
 */
export interface Progress {
  turn_id: string;
  /**
   * ToolCallID names the call this is about; empty means the turn itself.
   */
  tool_call_id?: string;
  /**
   * Name is the tool, sent only while a call is still ARRIVING — before
   * tool.requested exists to carry it. A subject that does not exist yet
   * has to name itself, or the report has nowhere to land.
   */
  name?: string;
  kind: string;
  done: number /* int */;
  total?: number /* int */;
}
/**
 * SessionRenamed is the name a person gave, which beats the one derived
 * from the first question. Empty gives the derived title back.
 */
export interface SessionRenamed {
  name: string;
}
/**
 * TurnCompleted ends a turn with one of the Stop* reasons.
 */
export interface TurnCompleted {
  turn_id: string;
  reason: string;
  /**
   * Usage is what the turn cost. Absent when the provider did not report
   * it, which is why it is a pointer: zero tokens and unknown tokens are
   * different facts and a client shows them differently.
   */
  usage?: Usage;
  /**
   * Completion is what was and was not checked. Absent when the turn had
   * no definition of done, which is why it is a pointer: "nothing to
   * check" and "checked, all met" are different facts.
   * It travels on the wire because it is the guarantee that survives a
   * model claiming success in prose. The text can lie; this cannot.
   */
  completion?: Completion;
}
/**
 * Completion is the state of the done criteria when a turn ended.
 */
export interface Completion {
  /**
   * Verification is the single-criterion seal: clean, passed, failed,
   * stale or unavailable.
   */
  verification: string;
  /**
   * Met and Unmet name the criteria, so a client can show which.
   */
  met?: string[];
  unmet?: string[];
  /**
   * Unavailable are criteria that could not be run at all. Different from
   * unmet, and shown differently: nothing was learned about them.
   */
  unavailable?: string[];
  /**
   * TouchedProtected are paths that are part of how the work is measured
   * and were written this turn. Never omitted when present.
   */
  touched_protected?: string[];
}
/**
 * Usage is the token accounting for a turn.
 * InputTokens is CUMULATIVE across the turn's rounds: every round re-sends
 * the context, so a forty-round turn sums forty readings of it. That is the
 * right number for what a turn COST and the wrong one for how full the
 * context is — a client that divided it by the window showed `ctx 175%`.
 */
export interface Usage {
  input_tokens: number /* int */;
  output_tokens: number /* int */;
  cache_read_tokens?: number /* int */;
  cache_write_tokens?: number /* int */;
  /**
   * ContextTokens is what the assembled context costs NOW — not summed,
   * and stated by the daemon rather than derived by a client.
   * It is the same estimate the compaction trigger reads, deliberately:
   * a meter and a threshold that disagree are worse than either alone,
   * because the person sees the summary happen at a number the screen
   * never showed. Provider counts could not give this — the two families
   * disagree about whether input_tokens already includes the cached
   * prefix, so the same context reads differently depending on who
   * answered.
   */
  context_tokens?: number /* int */;
}
/**
 * SessionCompacted records a context compaction.
 */
export interface SessionCompacted {
  from_seq: number /* uint64 */;
  to_seq: number /* uint64 */;
  /**
   * Messages is how many were replaced by the summary, and Kept how many
   * survived it. "Earlier history was summarised" says that something
   * happened; these say how much, which is the difference between a
   * notice and an answer.
   */
  messages?: number /* int */;
  kept?: number /* int */;
}
/**
 * SkillLoaded is one skill body appended to the turn.
 * Name and WhenToUse, and not the path: the event log is read by another
 * client, possibly on another machine, and an absolute path from the
 * machine that wrote it is not a fact there. Which root a skill came from
 * is a question `--dump-prompt` and the filesystem answer; which skill
 * fired is the one nothing answered.
 */
export interface SkillLoaded {
  name: string;
  when_to_use?: string;
}
/**
 * ContextBand is the context crossing a threshold on the way to being
 * summarised.
 * The model is told this already, and has been for a while. The PERSON was
 * not, so the summary arrived as a line saying it had happened — after the
 * fact, with no warning that it was coming and no way to finish a thought
 * first.
 * Fraction is of the BUDGET, not of the window: the budget is the space
 * before compaction, so 0.80 means eighty per cent of the way to a summary.
 * Against the window it would be a number about a limit that never arrives.
 */
export interface ContextBand {
  band: number /* int */;
  fraction: number /* float64 */;
}
/**
 * SessionResumed names the conversation the events after it came from.
 * Turns is what happened there, counted before the replay rather than by
 * the reader, so a client that joins late reads the same number as one that
 * was there.
 */
export interface SessionResumed {
  source_id: string;
  turns: number /* int */;
  started_at?: string;
}
/**
 * SessionModeChanged announces a behavioural mode switch.
 * Previous is empty on the very first announce, where there was nothing to
 * come from. Carried alongside Mode so the transcript shows the transition
 * rather than only the destination.
 */
export interface SessionModeChanged {
  previous?: string;
  mode: string;
  /**
   * SandboxMode is the technical half the switch just installed.
   * Carried rather than derived by the client, for the same reason the
   * mode name is derived from the pair on the daemon: the mapping has one
   * home. A client computing it from the name would be a second copy of
   * the table, and the copy is what drifts.
   * Without it the top bar went on announcing the boundary the session
   * was created with — and §2.1 of client-tui calls the sandbox field the
   * one place where being wrong is dangerous.
   */
  sandbox_mode: string;
}
