#!/usr/bin/env bash
# Gera o esqueleto da seção de uma versão, a partir dos commits desde a última
# tag.
#
# Esqueleto, e não o texto. O que este repositório guarda de mais valioso nos
# changelogs é o **porquê** — "a recusa era honesta mas instruía o abandono" não
# está em nenhum assunto de commit e não sai de nenhum gerador. O que sai é a
# parte mecânica: quais PRs entraram, agrupados, com o número ao lado.
#
# Um gerador que tentasse escrever o porquê produziria uma frase plausível sobre
# uma decisão que ninguém tomou, que é pior que uma lista sem frase nenhuma.
set -euo pipefail

version="${1:-}"
if [ -z "$version" ]; then
  version="$(./scripts/version.sh)" || exit 1
fi

# O idioma e argumento porque o changelog existe nos dois, como o README, com o
# ingles canonico. Gerar so um deixaria o outro para alguem lembrar de escrever a
# mao — e o que ninguem lembra e exatamente o que este gerador existe para tirar
# das costas de alguem.
lang="${2:-en}"
case "$lang" in
  en|pt) ;;
  *) echo "changelog: idioma '$lang' nao existe; use en ou pt" >&2; exit 1 ;;
esac

last="$(git describe --tags --abbrev=0 2>/dev/null || true)"
range="${last:+$last..}HEAD"

section() {
  local prefix="$1" title="$2"
  local body
  body="$(git log --format='%s' "$range" \
    | grep -E "^${prefix}(\([^)]+\))?!?: " \
    | sed -E "s/^${prefix}(\([^)]+\))?!?: //" \
    | sed -E 's/^(.*) \(#([0-9]+)\)$/- **\1** (#\2)/' \
    | sed -E 's/^([^-].*)$/- **\1**/' || true)"
  [ -z "$body" ] && return 0
  printf '\n### %s\n\n%s\n' "$title" "$body"
}

# O mes por extenso, em portugues, sem depender de locale: `date +%B` devolve
# "August" numa maquina em ingles e "agosto" noutra, e um changelog cujo idioma
# muda com a maquina de quem gera nao e um changelog, sao dois.
if [ "$lang" = pt ]; then
  meses=(janeiro fevereiro marco abril maio junho julho agosto setembro outubro novembro dezembro)
  mes="${meses[$(( 10#$(date +%m) - 1 ))]}"
  printf '## %s — %s de %s de %s\n' "${version#v}" "$(date +%-d)" "$mes" "$(date +%Y)"
else
  months=(January February March April May June July August September October November December)
  month="${months[$(( 10#$(date +%m) - 1 ))]}"
  printf '## %s — %s %s %s\n' "${version#v}" "$(date +%-d)" "$month" "$(date +%Y)"
fi

if [ "$lang" = pt ]; then
  section feat 'Adicionado'; section fix 'Corrigido'
  section refactor 'Mudado'; section perf 'Mudado'
  section docs 'Documentação'; section test 'Testes'
  section chore 'Manutenção'; section build 'Manutenção'; section ci 'Manutenção'
else
  section feat 'Added'; section fix 'Fixed'
  section refactor 'Changed'; section perf 'Changed'
  section docs 'Documentation'; section test 'Tests'
  section chore 'Maintenance'; section build 'Maintenance'; section ci 'Maintenance'
fi

if [ "$lang" = pt ]; then
  printf '\n> Esqueleto gerado por `scripts/changelog.sh`. **Cada linha ainda precisa\n'
  printf '> do porquê** — o que mudou sai do commit, a razão de ter mudado não sai de\n'
  printf '> lugar nenhum automaticamente.\n'
else
  printf '\n> Skeleton generated by `scripts/changelog.sh`. **Every line still needs its\n'
  printf '> why** — what changed comes from the commit, the reason for changing it comes\n'
  printf '> from nowhere automatically.\n'
fi
